### ISSUE TITLE
Optional: Add an option to only tune one part of the model 

### ISSUE THREAD

**Issue by PhilippBach** [OliverSchacht/AutoDoubleML#4]
Hi @OliverSchacht ,

just as an idea... maybe it makes sense to optionally let users provide separate tuning times for the different learners, e.g., through a `tune_time` dictoinary that maps the tuning time to each of the nuisance components `ml_m`, `ml_l` etc. 

I think, it's not necessarily the case that the tuning time should be split equally across these tasks

**Comment by OliverSchacht** [comment]
Yes, maybe the parameter `time` should be renamed to `tune_time` and should be int, dict or None, with dict being a dictionary of the nuisance components.

**Comment by PhilippBach** [comment]
I've been playing around with it a bit and will add a commit in the next hour...
